kubicorn/kubicorn

bootstrap/1.7.0_ubuntu_16.04_master.sh

Hat tip to https://github.com/kelseyhightower/kubeadm-single-node-cluster

Let's get Calico running so that Kubernetes actually starts up.

---

Makefile

Removes bootstrap.go and flips default ordering

Fix Makefile ordering and remove bootstrap.go

---

.gitignore

Remove bootstrap/bootstrap.go

---

README.md

updates overview, adds link to walkthrough

---

cmd/list.go
state/fs/impl.go
state/interface.go

* Adds a subcommand to list the states present in the state store

Add list sub-command

---

README.md

adds link to walkthrough video

---

bootstrap/bootstrap.go
cluster/validate.go
cmd/apply.go
cmd/getconfig.go
cutil/initapi/init.go
cutil/initapi/ssh.go
cutil/initapi/validate.go
cutil/kubeadm/token.go
examples/aws.go
profiles/simpleamazon.go

Adding token generation

---

Makefile
cloud/digitalocean/reconciler.go

The idea being to run `make vet` on CI in #68.

Add go-vet task and fix temporary vet error.

---

README.md

Random Typo PR

---

cutil/kubeconfig/kubeconfig.go

This should be refactored to be better but works around the issue in #76 for now
What I would ultimately like to do is inspect the key to determine if it's password protected, attempt to read from ssh-agent and then fall back to ask for password. I need to read more `crypto/ssh` stuff first.

Fix #76 -- Prompt for ssh key passphrase

---

README.md

Adding Deep Dive! Thanks @dmueller2001

---

scripts/headers.sh

Fixes #133 
Should be much better right now. I tested locally and it doesn't duplicate for me. If it happens for you, please let me know, I'll try harder.

Fix make headers

---

AUTHORS
docs/BUILD.md

Based on the documentation @arashkaffamanesh wrote in #77 and #78 i rewrote this documentation. I also added a description of the Docker build script and added some extra information.
There might still be a few spelling errors here and there. Just let me know what if there are any comments.

Build documentation

---

bootstrap/bootstrap.go
cloud/digitalocean/model.go
cloud/digitalocean/resources/droplet.go

Patch for hostnames

---

README.md

Because I couldn't help myself.
@kris-nova please review

Fix two minor typos in README

---

cutil/scp/scp.go

When you apply state, in case of DO, it will try to use scp to copy meshbird temp files. If your key is encrypted it will ask you for password many times before it becomes available.
This fix implements ssh-agent for scp. In case ssh-agent is available and has password, you will not be asked for password to check and copy files.

scp: make scp use ssh-agent

---

cmd/completion.go
cmd/root.go
cutil/logger/logger.go

Fixes #112 
Make our logs great again!

logger: implement lolgopher

---

bootstrap/digitalocean_k8s_ubuntu_16.04_master.sh
bootstrap/digitalocean_k8s_ubuntu_16.04_node.sh
cutil/kubeconfig/kubeconfig.go

K8s timeout

---

Makefile

Added the linting functionality as requested in #142.

Added golint to makefile

---

cutil/initapi/ssh.go
cutil/kubeconfig/kubeconfig.go
cutil/scp/scp.go

When asking for the password it was giving errors on windows without asking for a password. Fixed thanks to @xmudrii.

Fixed problem with asking for password on windows.

---

cmd/delete.go
cutil/logger/logger.go

Resolves https://github.com/kris-nova/kubicorn/issues/27.
Above issue seemed simple enough for my first contribution in Golang. @kris-nova: please provide feedback on code quality. Would you also suggest to factorize the anonymous function that takes care of printing the visual cue "." into a package? If so, where would you see good fit?

Integrate visual indicator that the cluster destroy action is in progress.

---

docker/build.sh

Added a flag to specify the make command to be run.

Docker build command updated

---

cutil/compare/compare_test.go

Pretty basic testing for compare package

Basic testing for compare package

---

README.md
cloud/digitalocean/godoSdk/sdk_test.go
docs/do/walkthrough.md
docs/envar.md
test/digitalocean/ubuntu_cluster_test.go

Officially, the company name is `DigitalOcean`, so I thought it would be better to follow it, it looks better. :D

do: fix company name typo

---

docs/MAKE.md

Fixes #196 
This is my try on `make` docs, suggestion appreciated :)
I think we got everything covered with this.

docs: Make docs

---

Makefile

Running `make gofmt` now fixes the format and imports of go files

Improve gofmt task

---

.travis.yml

With this change this is the output in travis

Use travis jobs

---

Makefile
scripts/bump-version.sh

Closes #69 
I found this elegant solution that doesn't seem bad and it works.

makefile: bump version

---

.travis.yml
Makefile
bootstrap/bootstrap.go
cutil/logger/logger.go
cutil/logger/logger_test.go
scripts/ci-checks.sh

Add check stages in travis-ci

---

scripts/headers.sh

Fix sed command in osx

---

docs/ISSUE_TEMPLATE.md

Addresses this #227
Kubicorn --version is not there yet, but I am adding this command line flag as well in a separate PR.

added issue template file

---

bootstrap/vpn/meshbirdMaster.sh
bootstrap/vpn/meshbirdNode.sh

fixes #225
Moved MESHBIRD_KEY variable from meshbirdMaster.sh => meshbirdNode.sh

added MESHBIRD_KEY to node.sh script 

---

.circleci/config.yml

Closes https://github.com/kris-nova/kubicorn/issues/157

Enable Circle CI

---

docs/ISSUE_TEMPLATE.md

Fixes #232
@kris-nova, I tried to clean up some of the HTML tags. PTAL.

clean up HTML tags in issue template

---

cloud/digitalocean/resources/droplet.go

do: remove droplets on sigint

---

cutil/README.md

Documentation for validation added in #214 
Happy to move this somewhere else if desired

Add API validation documentation to cutil's README

---

docs/SEMVER.md

So i made a small first draft of what could be the backwards compatibility promise based on [Semver](http://semver.org)  (#14) . Please feel free to provide feedback. Anything is welcome, things that should be added, things that should be specified in specific ways, things that need to be improved, etc.

[WIP] First draft of backwards compatibility promise

---

docs/Maintainers.md

Added draft for maintainers doc

---

cutil/parser/examples_test.go
cutil/parser/fileresource.go
cutil/parser/fileresource_test.go
cutil/parser/httpresource.go
cutil/parser/localresource.go

implements a simple file parser as required by #42 
if merged please create new issue to add S3 support

simple file parser/fetcher

---

docs/Maintainers.md

Fixed a little typo in Maintainers file :D

docs: fix typo in maintainers

---

cutil/scp/scp.go

This should improve ssh-agent for SCP.
Closes #270

Fix ssh-agent for SCP

---

cutil/parser/examples_test.go
cutil/parser/fileresource.go
cutil/parser/fileresource_test.go
cutil/parser/httpresource.go
cutil/parser/localresource.go

Converted return from []byte to string

---

README.md

Added google walkthrough to README.md

---

cloud/amazon/resources/keypair.go
docs/envar.md

KUBICORN_FORCE_DELETE_KEY envvar added

---

state/filenames.go
state/fs/impl.go
state/jsonfs/impl.go
state/jsonfs/impl_test.go

Wanted to get a PR out to review the approach for #183 
I added a JSONFileSystemStore that's heavily influenced by FileSystemStore. Assuming this is the way to go, in subsequent PRs I will update the various commands that write to a state store to also write to a JSON state store as well as updating the bash scripts to look at the JSON file.

Write cluster as JSON

---

docs/reconciler-proposal/kris-1/interface.go

CC @prateekgogia @xmudrii @roberthbailey

New interface proposal 

---

cloud/digitalocean/droplet/resources/ssh.go

This should fix error reported in #306 
Closes #306

do: check ssh keys by fingerprints

---

AUTHORS
apis/cluster/cluster.go
bootstrap/bootstrap.go
cloud/azure/azureSDK/sdk.go
cloud/azure/public/model.go
cloud/azure/public/resources/resource.go
cloud/azure/public/resources/resourcegroup.go
cloud/azure/public/resources/stub
cloud/azure/public/resources/virtualnetwork.go
cmd/create.go
cutil/reconciler.go
docs/aws/walkthrough.md
docs/azure/walkthrough.md
docs/do/walkthrough.md
docs/google/walkthrough.md
profiles/ubuntuazure.go

[WIP] Azure cloud provider implementation

---

apis/cluster/internetgw.go
cloud/amazon/public/resources/autoscalegroup.go
cloud/amazon/public/resources/internetgateway.go
cloud/amazon/public/resources/keypair.go
cloud/amazon/public/resources/launchconfiguration.go
cloud/amazon/public/resources/securitygroup.go
cloud/amazon/public/resources/subnet.go
cloud/amazon/public/resources/virtualprivatecloud.go
profiles/centosamazon.go
profiles/ubuntuamazon.go

Currently neither create or update works for AWS. This PR is fixing both and allows autoscaling (upscale and downscale) the cluster - and reusing/checks for existing resources in case of updates.

Fixing cluster create and update(upscaling/downscaling clusters) for AWS

---

Makefile
cloud/google/compute/resources/compute.go
cutil/task/task.go
profiles/ubuntugooglecompute.go
state/filenames.go
state/jsonfs/impl.go
state/jsonfs/impl_test.go

Lint script was broken. This fixes it and adds some small lint fixes.

Fixed Makescript lint

---

state/fs/impl_test.go

adds test for fs state storage. Mostly a conversion of the json tests.
not sure if Closes #140

fs state storage tests

---

cloud/google/compute/model.go
cloud/google/compute/model_test.go
cloud/google/compute/resources/compute.go
cloud/google/compute/resources/instancegroup.go
cloud/google/compute/resources/instancegroup_test.go
cloud/google/compute/resources/resources.go

The instanced are gone and everything is now using instance groups. This fixes #328 and #292.

Change instances to managed instance groups.

---

docs/ark_integration.md

Tried to capture the flow for Ark and Kubicorn integration. Once, we are ok with it, I can request Ark folks to provide feedback.
#195

[RFC] Ark and Kubicorn integration

---

README.md

Docs have moved, so links were all 404.  Corrected & tidied up some typos.

Updated readme.md for new doc locations

---

docs/_config.yml
docs/_includes/footer.html
docs/_layouts/documentation.html

As reported by Marko on Slack.
- docs/_includes/footer.html

Footer fix

---

docs/_layouts/home.html

Commented out the whole `Friends of Kubicorn` section.

Hidin' frens

---

docs/_includes/footer.html
docs/_includes/header.html

Makes burger menu close on click. #345

close burger on click

---

docs/_includes/header.html

moved <button> a few lines up

---

test/digitalocean/centos_cluster_test.go
test/digitalocean/ubuntu_cluster_test.go

Small PR to fix the tests (for DO, AWS is fixed as a side effect of PR #371) with the new profiles.

Test profile fix for DO

---

profiles/centosamazon.go
profiles/ubuntuamazon.go

Fixes a typo preventing the master from being able to hit the node (proxy, logs, exec)

Adjust the security group to allow master to node

---

cloud/atomic_reconciler.go
cutil/signals/signals.go

Fix related to [this](https://github.com/kris-nova/kubicorn/commit/d88323e67e9ac0ef19c41d29a2ff3e26c7a17d4d#diff-764f6fad5669b3a115a211204b0eea8a) issue.

Signal handling fix

---

test/cluster.go

test: use new reconciler interface for test package

---

cloud/digitalocean/droplet/model.go
cloud/digitalocean/droplet/resources/droplet.go
cloud/digitalocean/droplet/resources/firewall.go
profiles/ubuntudigitalocean.go

Partially Addresses #396 
It will allow us to specify tags instead of IP addresses for DO firewalls.

do: allow firewalls to use tags

---

profiles/ubuntudigitalocean.go

Minor ingress rule change/fix (master -> node) for DO

---

docs/_documentation/project-walkthrough.md

Fix the copy-paste mistake I made in the Project Walkthrough.

docs: fix files name

---

cmd/create.go

The --set flag in create command, should be
case insensitive.
Fixes #417

Improve create command --set flag

---

docs/_documentation/aws-walkthrough.md
docs/_documentation/envar.md

Sorry for the mess with the commits, I am sending this as a `patch` for #433 asked by @MyDigitalLife related to my previous PR - I am sending this from a surf trip from the middle of the Indian Ocean having an extremely poor internet connection - failed to update my fork, thus had to use GitHub UI ... sorry @MyDigitalLife again and also for missing the documentation update, thanks for pointing it out.

Aws credentials doc update related to #433 

---

docs/_layouts/home.html

Added pre-release badge to kubicon.io

---

cloud/google/compute/resources/instancegroup.go

**Why we need this PR**
Currently, when creating deleting a cluster on GCP, kubicorn does not delete instance templates.
This PR fix this.
**Notes for the reviewer** 
- Before deleting instance templates, it is necessary that the deletion of the referencing instance groups completes. To implement this wait loop I implemented the same wait loop already implemented in GetConfig.
- While making the change, I made also tsmall changes to allow the delete procedure to run without error even if resources are partially or totally already deleted (e.g. useful if you have to recover from an error).

Remove instance templates on kubicorn delete over GCP

---

docs/_layouts/home.html
docs/_site/index.html

Hey! I just started taking a look at kubicorn and spotted a typo while I was on the site. So here's a PR to fix it. :)
(At least I think so, anyway - considering the same text appears in multiple places it feels like there might be some autogeneration happening here.)

Fix typo: conrtibuting -> contributing

---

AUTHORS
Dockerfile
Makefile
bootstrap/bootstrap.go
cutil/kubeadm/token.go
cutil/namer/random.go
cutil/parser/fileresource.go
cutil/uuid/uuid.go

Build in Docker Container #119

---

cloud/amazon/public/resources/launchconfiguration.go

This could fix the issue reported on Slack channel.
Fixes #448 
/cc @kris-nova

aws: hotfix spot price

---

docs/README.md
docs/_documentation/project-walkthrough.md

Website structure documentation

---

README.md
docs/_site/documentation/do-walkthrough.html

Somebody suggested/requested an asciicast so I made one.

Asciicast quickstart - addresses #388

---

cloud/amazon/public/resources/autoscalegroup.go
cloud/amazon/public/resources/internetgateway.go
cloud/amazon/public/resources/keypair.go
cloud/amazon/public/resources/launchconfiguration.go
cloud/amazon/public/resources/routetable.go
cloud/amazon/public/resources/securitygroup.go
cloud/amazon/public/resources/subnet.go
cloud/amazon/public/resources/virtualprivatecloud.go
cloud/azure/public/resources/resourcegroup.go
cloud/digitalocean/droplet/resources/droplet.go
cloud/digitalocean/droplet/resources/firewall.go
cloud/digitalocean/droplet/resources/ssh.go
cloud/google/compute/resources/instancegroup.go
cutil/logger/logger.go
cutil/logger/logger_test.go
cutil/parser/fileresource.go
examples/amazon/basiccluster.go
examples/digitalocean/basiccluster.go
examples/google/compute/basiccluster.go

logger: implement success function

---

cloud/README.md
docs/_documentation/cloud-providers.md

This is a first attempt. Adding a new cloud provider requires touching a number of different places. Would appreciate corrections.

Updated cloud/README.md to describe how to add new cloud provider

---

README.md
docs/README.md
docs/_layouts/documentation.html
docs/_layouts/home.html

Also added to main site pages generated by Jekyll.

Fix packet walkthrough link

---

docs/_layouts/documentation.html

Fix Pcket typo

---

bootstrap/digitalocean_k8s_centos_7_master.sh
bootstrap/digitalocean_k8s_ubuntu_16.04_master.sh

Also rename PRIVATEIP to VPNIP.

Use DO's metadata service for public interface

---

docs/_documentation/cloud-providers.md

Fix broken links

---

bootstrap/amazon_k8s_centos_7_master.sh
bootstrap/amazon_k8s_centos_7_node.sh
bootstrap/amazon_k8s_ubuntu_16.04_master.sh
bootstrap/amazon_k8s_ubuntu_16.04_node.sh
profiles/amazon/centos_7.go

Adds cloud provider integration into the AWS profiles. If this approach works for others, then I can look at doing similar in at least GCP and Azure.
I have confirmed that dynamic PVCs are fulfilled with EBS volumes with this. I believe ELBs work too, but I haven't tested it yet.

AWS cloud provider support

---

cutil/kubeconfig/kubeconfig.go

@kris-nova no need for guilty anymore :D

kubeconfig: filepath instead of sprintf

---

AUTHORS
cmd/create.go

- defaulting to google instead of azure for profiles
- turning profile list back on
- updating authors file

updating create cmd

---

profiles/digitalocean/centos_7.go
profiles/digitalocean/ubuntu_16_04.go

This PR switches to new Droplets for both master and workers.
Previously, we've used 2GB Droplets for both master and workers.
With this PR we're shifting to $15, 2GB, 2 vCPU Droplet for master, and $10 2GB, 1 vCPU Droplets for Workers.

profiles, digitalocean: switch to new droplets

---

bootstrap/amazon_k8s_debian_stretch_master.sh
bootstrap/amazon_k8s_debian_stretch_node.sh
cmd/create.go
profiles/amazon/debian_stretch.go

This change adds a sample debian profile as described in https://github.com/kris-nova/kubicorn/issues/421

profiles: added debian stretch profile for aws

---

cmd/apply.go
cmd/delete.go
docs/_documentation/aws-walkthrough.md
docs/_documentation/envar.md

docs: add aws profile

---

AUTHORS
cmd/apply.go
cmd/getconfig.go
pkg/kubeconfig/kubeconfig.go
pkg/kubeconfig/kubeconfig_test.go

Working on SSH

---

cloud/amazon/public/resources/securitygroup.go
cmd/apply.go
cmd/create.go
cmd/delete.go
cmd/edit.go
cmd/getconfig.go
cmd/list.go
cmd/prompt.go
cmd/root.go
cmd/unicorn.go
cmd/version.go
pkg/agent/agent.go
pkg/agent/agent_test.go
pkg/cli/env.go
pkg/cli/options.go
pkg/cli/profiles_map.go
pkg/cli/state_store.go
pkg/cli/utils.go
pkg/kubeconfig/kubeconfig_test.go
pkg/uuid/uuid.go
state/git/cluster.json/config

moved some cli logic to pkg/cli, updated tests: pkg/agent/agent_test.go (to be a bit more clean, and fix issues running tests more than once) and pkg/kubeconfig/kubeconfig_test.go because tests assumes that local machine is ssh-able and so terminates prematurely and fails (fix allows it to be skippable).

 [library] enhancements; moved some (cmd) cli logic to (pkg) pkg/cli

---

cmd/explain.go

Currently, the `explain` command doesn't work with Git and S3 state stores. This PR replaces the old State Stores logic with a new one, implemented in the `cli` package.

cmd: add git and s3 state stores for explain cmd

---

README.md
docs/_documentation/envar.md

This var isn't in the code anymore.
Also changed the readme to reference the new docs.
Should we get rid of the old ones?

Remove KUBICORN_FORCE_DISABLE_SSH_AGENT from envvar.md

---

AUTHORS
apis/cluster/cluster.go
bootstrap/README.md
bootstrap/amazon_k8s_centos_7_master.sh
bootstrap/amazon_k8s_centos_7_node.sh
bootstrap/amazon_k8s_debian_stretch_master.sh
bootstrap/amazon_k8s_debian_stretch_node.sh
bootstrap/amazon_k8s_ubuntu_16.04_master.sh
bootstrap/amazon_k8s_ubuntu_16.04_node.sh
bootstrap/digitalocean_k8s_centos_7_master.sh
bootstrap/digitalocean_k8s_centos_7_node.sh
bootstrap/digitalocean_k8s_ubuntu_16.04_master.sh
bootstrap/digitalocean_k8s_ubuntu_16.04_node.sh
bootstrap/google_compute_k8s_ubuntu_16.04_master.sh
bootstrap/google_compute_k8s_ubuntu_16.04_node.sh
bootstrap/ovh_k8s_ubuntu_16.04_master.sh
bootstrap/ovh_k8s_ubuntu_16.04_node.sh
bootstrap/packet_k8s_ubuntu_16.04_master.sh
bootstrap/packet_k8s_ubuntu_16.04_node.sh
cloud/amazon/public/resources/launchconfiguration.go
docs/_documentation/envar.md
pkg/parser/fileresource.go

- Fixes unlimited hang during apply in AWS
- Fixes the camelcasing of the new API fields
- Fixes the bootstrap developer mode overrride envvar

Patch for new API

---

pkg/kubeconfig/kubeconfig.go

This PR simplifies the code and the behaviour of kubicorn. If the user has a running agent which has the needed key already in its ring, do not load the private key. So the user does not need to enter a passphrase. 
Closes #577

get rid of the passphrase if key is already in agent

---

cloud/google/compute/model_test.go
cloud/google/compute/resources/instancegroup_test.go
pkg/initapi/validate_test.go
pkg/kubeconfig/kubeconfig_test.go
pkg/local/env.go

Fixing issues with tests found after merge of #572. Some changes I am unsure of so guidance will be appreciated. Thank you.

[go tests] fixing a few go test issues, mostly likely due to recent changes

---

cloud/digitalocean/droplet/resources/droplet.go

digitalocean: fix cluster provisioning problems

---

cloud/amazon/public/resources/securitygroup.go
cloud/amazon/public/resources/subnet.go

partially addresses https://github.com/kubicorn/kubicorn/issues/545, added tag functions for security groups and subnets. 
note that some aws resources [do not support tags](https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/Using_Tags.html#tag-resources). this includes instance profiles, key pairs, launch configurations.
tested manually by creating cluster and ensuring resources are tagged.

cloud/amazon: added tags for security groups and subnets

---

AUTHORS
pkg/initapi/init.go

Patching validation for server pools

---

README.md
docs/_documentation/maintainers.md
docs/_layouts/home.html

docs: minor fixes

---

pkg/state/crd/impl.go
profiles/amazon/controller_ubuntu_16_04.go

Just working on hardening the controller deployment logic
closes #578

Controller bootstrap improvements

---

AUTHORS
pkg/parser/github.go

Fixes issue reporting in slack

Patching GitHub URL generating function to work with git submodules

---

pkg/reconciler.go
test/amazon/centos/centos_cluster_test.go
test/amazon/ubuntu/ubuntu_cluster_test.go
test/digitalocean/centos/centos_cluster_test.go
test/digitalocean/ubuntu/ubuntu_cluster_test.go

Did not test digitalocean, but at least it compiles now!
Tested ubuntu and centos on amazon. Centos needs [this pr](https://github.com/kubicorn/bootstrap/blob/master/amazon_k8s_centos_7_master.sh) to succeed.

Fix broken integration tests.

---

pkg/initapi/init.go
pkg/initapi/validate.go

initapi,do: add cluster name validation

---

cloud/digitalocean/droplet/resources/droplet.go
cloud/digitalocean/droplet/resources/firewall.go

Closes #618
Closes #607
This PR fixes the problem with the State Store file for DigitalOcean, which fixes deletion issues as well.

cloud,digitalocean: fix delete issue

---

docs/_documentation/ovh-walkthrough.md

Relates to https://github.com/kubicorn/kubicorn/issues/641.

Emphasize on regions being the same in openrc.sh and cluster.yaml for OVH

---

cloud/openstack/operator/generic/resources/securitygroup.go
cloud/openstack/operator/generic/resources/subnet.go

This PR tries to fix the panics mentioned in issues #647 and #649. As this is an urgent issue, I'm going to merge the PR once CI is green.

ovh: fix panics

---

cloud/openstack/operator/generic/resources/router.go

Tries to fix the problem described by @licarth in #655

Openstack: fix nil panics for routers

---

cloud/openstack/operator/generic/resources/router.go

OVH: fix panics try 2

---

AUTHORS
pkg/kubeconfig/kubeconfig.go
pkg/kubeconfig/kubeconfig_test.go
test/kubeconfig/config-1.yaml
test/kubeconfig/config-2.yaml
test/kubeconfig/config-3.yaml

Signed-off-by: Ashish Amarnath <ashish.amarnath@gmail.com>
What this PR does / why we need it:
This PR implements support for multicluster kubeconfig fixing https://github.com/kubicorn/kubicorn/issues/496
Which issue(s) this PR fixes (optional, in fixes #<issue number>(, fixes #<issue_number>, ...) format, will close the issue(s) when PR gets merged):
Fixes # 496

Support multi cluster kubeconfig

---

pkg/kubeconfig/kubeconfig.go

Signed-off-by: Ashish Amarnath <ashish.amarnath@gmail.com>

Set current-context to point to new cluster

---

cloud/amazon/public/resources/subnet.go

fixes https://github.com/kubicorn/kubicorn/issues/651

adds explicit retries to subnet tagging

---

cmd/apply.go
cmd/create.go
pkg/cli/swalker.go
pkg/cli/swalker_test.go
scripts/check-header.sh
scripts/headers.sh

Add cli.SwalkerWrite helper to handle conversion from string to
int/uint/bool types.
Fixes #673 
Signed-off-by: Andy Goldstein <andy.goldstein@gmail.com>

Add cli.SwalkerWrite helper

---

apis/cluster/cluster.go
cmd/apply.go
pkg/resourcedeploy/clusterdeployment.go
profiles/digitalocean/centos_7.go
profiles/digitalocean/controller_ubuntu_16_04.go
profiles/digitalocean/ubuntu_16_04.go

Added a `CloudManagerSecret` to Cluster API to enable CloudManagers, and specifically add DigitalOceans Cloud-Manager and CSI
Related PR for Bootstrap scripts: https://github.com/kubicorn/bootstrap/pull/23

Added a `CloudManagerSecret` to Cluster API to enable CloudManagers

---

cloud/digitalocean/droplet/resources/firewall.go

As this issue was present for several months already, I want to summarize what happened. This may be useful if we run into the problem again.
**Postmortem:**
* For a month or two now, the cluster creation process for DigitalOcean has been broken. Users trying to create a new cluster would get error such as:
```
2018-11-05T23:28:14+01:00 [✖]  Error during apply of atomic reconciler, attempting clawback: failed to create the firewall err: POST https://api.digitalocean.com/v2/firewalls: 500 Server was unable to give you a response.
```
* For the unknown reason, the Firewall creation would fail causing the whole cluster creation process to fail as well,
* The issue was initially reported on April 27, 2018 (#635) and fixed by June 13, 2018,
* When it was first reported, retrying to create a …

Fix Firewall and Cluster creation for DigitalOcean clusters

---

cloud/amazon/public/resources/securitygroup.go

For multi-node configurations, all members of the same security group
should be able to communicate with each other. Without this change,
communication between control plane nodes and worker nodes is
functional, but communication from one control plane node to another
control plane node is blocked, as is worker node to worker node. Overlay
networks such as Calico require node-to-node communications, and this
change allows these networks to function.
Signed-off-by: Andy Goldstein <andy.goldstein@gmail.com>

AWS: allow security group members to communicate

---

README.md

They really care about this. I've talked to them. They care.

pedantic correction of DigitalOcean

---

Makefile

otherwise, an error pop up:
vendor/github.com/json-iterator/go/config.go:107: undefined: sync.Map
Signed-off-by: Hui Luo <luoh@vmware.com>

upgrade golang to 1.9.3 to solve compile issue
