- cmd/create.go
`kubicorn create` was previously silent on completion reported in #17
This adds feedback and next steps to run `kubicorn apply`
> Add user feedback to create

- cloud/amazon/awsSdkGo/sdk.go
We set up our AWS so that the default account has little/zero permissions and we do everything through roles across accounts.  We also require MFA in a lot of places.  This magic incantation when creating the session makes the SDK act more like the aws command line tools.  
You can do something like `export AWS_DEFAULT_PROFILE=dev-joe` to set the profile to the one that you want to use and now kubicorn will pick it up.
> Support MFA and roles when doing auth

- .gitignore
- Makefile
- README.md
- docs/INSTALL.md
* There were a few hardcoded paths that seemed unecessary as they can be referred to from current directory
* Attempt to deal with go-bindata not being present ( took me a while to figure out what was going on )
* Make `bin/` dir before building with docker so at least its owned by non-root even if binaries are.
* Add bin/ to gitignore
* Update readme with install options
> Remove some hard coded paths in Makefile

- .travis.yml
- README.md
This should resolve issue #68 by adding travis.ci support.  It's free for opensource
so should be easily enabled by connecting travis.ci with the repo by somebody who has access ( @kris-nova ) to connect via oauth and authorize travis to the repo.
I figured it would be worth doing both `make test` and `make compile` to ensure both steps work in a fairly blank go environment on PRs/Merges.
> add support for travis.ci testing

- Makefile
- bootstrap/bootstrap.go
- cutil/kubeconfig/kubeconfig.go
Fixes #111 
Nobody is complaining on the issue so I gave it a try. I tested this myself and it's working.
I made it like this so if somebody is interested in the output, it can use `VERBOSE` variable to see what's happening (e.g. `VERBOSE=1 make gofmt`). It's not needed, but this way could satisfy everybody. If you have something against it I'll remove it. =)
Example:
```
18:08 in github.com/kris-nova/kubicorn on  silent-makefile [!] via 🐹 v1.9 on 🐳 v17.06.0-ce took 2s 
➜ make gofmt
18:08 in github.com/kris-nova/kubicorn on  silent-makefile [!] via 🐹 v1.9 on 🐳 v17.06.0-ce 
➜ VERBOSE=1 make gofmt
gofmt -w ./apis
gofmt -w ./bootstrap
gofmt -w ./cloud
gofmt -w ./cmd
gofmt -w ./cutil
gofmt -w ./docs
gofmt -w ./examples
gofmt -w ./logger
gofmt -w ./namer
gofmt -w ./profiles
gofmt -w ./state …
```
> makefile: silent makefile by default

- README.md
This PR fixes link for the Go ReportCard in the Readme file. Currently Go Report Card is showing badge for kris-nova/klone and linking to nivenly/kamp
> readme: fix go reportcard link

- Makefile
- scripts/check-header.sh
Partially addresses #88 
This implements `check-header` command for Makefile. Running `make check-header` returns the following:
```
incorrect license header: ./bootstrap/bootstrap.go
incorrect license header: ./bootstrap/inject.go
incorrect license header: ./cutil/hang/ratio.go
incorrect license header: ./cutil/kubeadm/token.go
incorrect license header: ./cutil/initapi/init.go
incorrect license header: ./cutil/initapi/ssh.go
incorrect license header: ./cutil/initapi/validate.go
...
```
It uses external script, located at the `./scripts` directory, but I think it's easiest and best? way to do this.
If you have anything against this way, I'll revisit this PR :+1:
> makefile: check-header implementation

- AUTHORS
- Makefile
👋  I'm new here! I saw a tiny thing I may be able to help with. Feel free to ignore :) 
When generating the AUTHORS file the Makefile relies on a git log that may or may not be representative of the valuable data. It's very easy to omit configuration of the git config which easily makes for duplicate authors.
This change tweaks the output of the sorted git log, pipes the values into egrep that relies on an inverse filter that's easily extended. This change should not be seen as a long-term solution as the regex could quickly grow out of hand.
> Tweak make authorsfile script and remove duplicate authors

- scripts/check-header.sh
We've added `make check-header` to CI so license headers are tested on every PR/commit.
The problem is that in current implementation it doesn't return error code so it will pass every time.
I've changed this to return code 1 if incorrect header is found. In that case CI will fail.
> scripts: make check-header return exit code

- docker/build.sh
A small addition to the Docker build script so all available flags are documented an can be called using a -h or --help flag.
> Added help command to script to document flags

- Gopkg.lock
- cmd/completion.go
- cmd/root.go
- vendor/github.com/spf13/cobra/.travis.yml
- vendor/github.com/spf13/cobra/README.md
- vendor/github.com/spf13/cobra/args.go
- vendor/github.com/spf13/cobra/bash_completions_test.go
- vendor/github.com/spf13/cobra/cobra/cmd/add.go
- vendor/github.com/spf13/cobra/cobra/cmd/add_test.go
- vendor/github.com/spf13/cobra/cobra/cmd/golden_test.go
- vendor/github.com/spf13/cobra/cobra/cmd/init_test.go
- vendor/github.com/spf13/cobra/cobra/cmd/license_agpl.go
- vendor/github.com/spf13/cobra/cobra/cmd/license_apache_2.go
- vendor/github.com/spf13/cobra/cobra/cmd/license_bsd_clause_2.go
- vendor/github.com/spf13/cobra/cobra/cmd/license_bsd_clause_3.go
- vendor/github.com/spf13/cobra/cobra/cmd/license_gpl_2.go
- vendor/github.com/spf13/cobra/cobra/cmd/license_gpl_3.go
- vendor/github.com/spf13/cobra/cobra/cmd/license_lgpl.go
- vendor/github.com/spf13/cobra/cobra/cmd/license_mit.go
- vendor/github.com/spf13/cobra/cobra/cmd/licenses.go
- vendor/github.com/spf13/cobra/cobra/cmd/root.go
- vendor/github.com/spf13/cobra/cobra/cmd/testdata/main.go.golden
- vendor/github.com/spf13/cobra/cobra/cmd/testdata/root.go.golden
- vendor/github.com/spf13/cobra/cobra/cmd/testdata/test.go.golden
- vendor/github.com/spf13/cobra/cobra_test.go
- vendor/github.com/spf13/cobra/command.go
- vendor/github.com/spf13/cobra/zsh_completions.go
- vendor/github.com/spf13/cobra/zsh_completions_test.go
This PR implements completion code generation for bash and zsh shells.
For now, it only offers basic set of features - completion for commands and flags. Next coming up (let's merge this as it is?) is resources completion from `_state` and similar locations. 
Here is a short guide how to use this:
```
completion is used to output completion code for bash and zsh shells.
Before using completion features, you have to source completion code
from your .profile. This is done by adding following line to one of above files:
source <(kubicorn completion SHELL)
Valid arguments for SHELL are: "bash" and "zsh".
Notes:
1) zsh completions requires zsh 5.2 or newer.
2) macOS users have to install bash-completion framework to utilize
completion features. This can be done using homebrew:
brew install …
```
> completion: generation of bash and zsh completion codes

- examples/aws.go
AWS bootstrap example is failing due to wrong bootstrap script name.
This PR fixes bootstrap script name from `1.7.0_ubuntu_16.04_master.sh` to `amazon_k8s_ubuntu_16.04_master.sh` and `1.7.0_ubuntu_16.04_node.sh` to `amazon_k8s_ubuntu_16.04_node.sh`
> Fix bootstrap script name to existing one

- docker/Dockerfile
- docs/BUILD.md
A update to [lolgopher](https://github.com/kris-nova/lolgopher) added a dependency on ` libncurses5-dev` so i added this to the documentation and to the docker build script. Credit to @xmudrii for finding this (https://github.com/kris-nova/lolgopher/issues/11).
> Added dependency on libncurses5-dev in documenation and Docker build

- cloud/digitalocean/resources/ssh.go
- cutil/initapi/ssh.go
- cutil/kubeconfig/kubeconfig.go
Fixes #137 
Beside #137, allowed SSH key reusability!
Everything is supposed to work correctly now, tested locally. If you don't mind, give it a try just to be sure non-encrypted keys are working as indeed too
> digitalocean: allow usage of encrypted keys

- cutil/kubeconfig/kubeconfig.go
- cutil/kubeconfig/kubeconfig_test.go
Fixes issue that if you don't have `~/.kube` dir on local machine it will fail copying kubeconfig from the remote.
> kubeconfig: create .kube dir if it doesn't exist

- examples/digitalocean/basiccluster.go
Digital ocean doesn't allow points in the name. The error thrown atm is not very descriptive but it there should be a extra field(Internaldesc) given by the response from digital ocean that explains the message better.
> Fixed problem with ServerPool name format.

- cutil/logger/fabulous.go
- cutil/logger/fabulous_windows.go
- cutil/logger/logger.go
lolgopher doesn't seem to work on Windows, due to ncurses.h library being not available for platform. When you try to build/install kubicorn, you will get the following error:
```
go\src\github.com\kris-nova\kubicorn\vendor\github.com\kris-nova\lolgopher\has_colors.go:4:11: fatal error: ncurses.h: No such file or directory
// #include <ncurses.h>
^~~~~~~~~~~
compilation terminated.
```
This PR disables lolgopher for Windows.
Thanks to @MyDigitalLife for finding it out and providing logs.
> logger: disable lolgopher on windows

- apis/cluster/api.go
- apis/cluster/auth.go
- apis/cluster/cluster.go
- apis/cluster/network.go
- apis/cluster/serverpool.go
- cloud/amazon/reconciler.go
- cloud/amazon/resources/autoscalegroup.go
- cloud/amazon/resources/keypair.go
- cloud/amazon/resources/launchconfiguration.go
- cloud/amazon/resources/routetable.go
- cloud/amazon/resources/securitygroup.go
- cloud/amazon/resources/subnet.go
- cloud/digitalocean/reconciler.go
- cloud/digitalocean/resources/droplet.go
- cloud/digitalocean/resources/ssh.go
- cmd/apply.go
- cmd/delete.go
- cmd/getconfig.go
- cutil/initapi/ssh.go
- cutil/kubeconfig/kubeconfig.go
- cutil/reconciler.go
- cutil/scp/scp.go
- examples/amazon/basiccluster.go
- examples/digitalocean/basiccluster.go
- profiles/simpleamazon.go
- profiles/simpledigitalocean.go
- state/fs/impl.go
- test/amazon/ubuntu_cluster_test.go
- test/digitalocean/ubuntu_cluster_test.go
There are still 196 warnings after this. But these are all just missing comments.
> Renamed variable names to fix lint warnings

- cmd/apply.go
- cmd/completion.go
- cmd/create.go
- cmd/delete.go
- cmd/getconfig.go
- cmd/list.go
- cmd/root.go
Fixes #128 
Fixes #26 
Downsides:
* Current version supports only `./_state` or using environmental variables. This should not be a big thing, even if it stays.
* Profiles are typed in as constant. We will fix this once we better know how we will manage profiles. We will probably need an command to list all profiles.
Available for `--name` and `--profile` flags.
> Bash and Zsh completion for flags

- cloud/digitalocean/resources/ssh.go
This should fix the error where even in cases such as corrupted SSH key, user would get key not existing instead of appropriate error.
> godo: parse ssh errors

- AUTHORS
- bootstrap/amazon_k8s_ubuntu_16.04_master.sh
- bootstrap/digitalocean_k8s_ubuntu_16.04_master.sh
Some Linux distributions have deprecated the use of ifconfig and route in favor of the software suite iproute2. The command ip should be used instead of ifconfig.
> ifconfig is deprecated and should be avoided

- docker/build.sh
ATM the docker build script only worked in the docker folder. Now you can just call it from the root like `./docker/build.sh`.
> Fixed docker build in other directories.

- CONTRIBUTING.md
I am noticing that some PR's are missing license headers. This
causes the CI to fail and ulitimately it wastes time.
Adding some documentation on how to validate and update headers.
> Document license header requirement

- Makefile
Instead of setting a black background on the make commands (making them impossible to read without highlighting them), set the text color to be green.
> Makefile: Green text instead of black background

- cmd/version.go
adds a new version command, this should also work with go get.
Sample output - 
$ kubicorn version
`Kubicorn version:  {"Version":"0.0.003","GitCommit":"457a1e9618a96671fc3c54d16e40b8c5ef6d5220\n","BuildDate":"2017-08-09 19:19:01.508842266 +0000 UTC","GOVersion":"go1.8.1","GOARCH":"amd64","GOOS":"darwin"}`
> Add version command

- scripts/headers.sh
Removed sed command on OSX, replaced with echo and simplified logic.
Running sed command on OSX doesn't add the header in correct format. I have removed the logic for checking OS, using sed and replaced with echo. Verified on OSX and Linux.
> Fixes make update-headers command on OSX

- cutil/kubeconfig/kubeconfig.go
Partially addresses #270 
We should call `getSigner` only if ssh agent is not enabled.
> Fixes kubeconfig.go ability to use ssh agent

- cloud/amazon/resources/keypair.go
Minor message change - removed subnet from the log message - and a question.
I have found this while investigating a `potential ???` issue and will track this one below in a different issue and sent a fix in case it's valid - it's just a heads un and very much interested in your opinion. In case a user has changed/regenerated his local keys, and a cluster is created with the new key pair but same name, the old keypairs are still available on the AWS side. The cluster is created (with the same name - in my case by a CI system) but the end user/test suite wont be able to SSH into it. Obliviously this is up to interpretation and not a likely scenario - just wandering whether it makes sense to check or log whether the user's key has changed and the public fingerprints are different. 
Thank …
> Minor log message change - removeing "subnet"

- cmd/create.go
- profiles/centosamazon.go
Minor fix for output text and fix for:
```
2017-08-15T13:45:21+02:00 [✖]  Error during apply! Attempting cleaning: ValidationError: AMI ami-0c2aba6c  is invalid: Invalid id: "ami-0c2aba6c "
status code: 400, request id: 378bd487-81af-11e7-b83d-f1bc3586d1ac
```
> Fixed output format for apply command and removed whitespace in image id

- cmd/apply.go
- cmd/create.go
- cmd/delete.go
- cmd/getconfig.go
- cmd/root.go
This PR fixes Shell completions for cluster names, as `-n` flag got removed back in #265
> cmd: fix name bash completions

- cloud/digitalocean/droplet/resources/ssh.go
If SSH key doesn't exist in DO account, it will not be created and instead, the following error will be returned:
```
2017-08-18T21:54:11+02:00 [✖]  Error during apply of atomic reconciler, attempting clawback: strconv.Atoi: parsing "": invalid syntax
2017-08-18T21:54:11+02:00 [!]
2017-08-18T21:54:11+02:00 [!]  Attempting to backtrack and cleanup created resources.
2017-08-18T21:54:11+02:00 [!]
2017-08-18T21:54:11+02:00 [▶]  ssh.Delete
2017-08-18T21:54:11+02:00 [▶]  ssh.Render
2017-08-18T21:54:11+02:00 [✖]  Unable to commit state store: Nil cluster spec
```
This PR should fix this behavior - i.e. keys will be created normally.
> do: fix ssh key creation bug

- apis/cluster/cluster.go
- cloud/google/compute/resources/compute.go
- cloud/google/compute/resources/compute_test.go
- cmd/create.go
- cmd/root.go
- cutil/defaults/defaults.go
- profiles/ubuntugooglecompute.go
For GCE atm you needed to have the kubicorn name and the project-id be the same. This PR adds a parameter cloudid to the create command to be able to set the project-id differently then the kubicorn name. It also requires the cloudid parameter but only for GCE.
Closes #291
> Added cloudid option

- cutil/uuid/uuid.go
- profiles/centosamazon.go
- profiles/ubuntuamazon.go
This PR is related to #286 - a time ordered UUID generator is added and the unique name is applied when specifying the name of the security group in the default clusters. 
Ideally I wanted to have this included in the `securitygroup.go` - however while working on cluster update found this causes different issues during reconcile and state management. Once the new refactor is finished and also a different cluster update PR is merged we can return to this - for now this leaves the uniqueness generation (as AWS does) to the end user's discretion, and serves as an example in the cluster templates, and providing a UUID generator.
> Kubicorn #286 - Use unique name (within VPC/region) for a security group

- Makefile
This adds a Makefile command to run a bash script linter.
Once merged we can add issues to fix existing lint errors before we 
enforce it.
> add bash lint check to Makefile

- docs/_config.yml
- docs/_layouts/documentation.html
This refers to the bottom part of documentation pages.
Closes #338. 
Someone please check that the g+ share link is working, I don't have a g+ account.
> Removed author box; fixed social media links

- apis/cluster/serverpool.go
- cloud/amazon/public/resources/launchconfiguration.go
This feature is adding the option to create the cluster using AWS spot instances. For `node` type instances (`cluster.ServerPoolTypeNode`) the launch configuration is created with a spot request and submitted. 
This feature is a potential pre-requisite for #321 in order to be able to run e2e nightly integration tests at a considerable cheaper price. 
There are several outcomes (handled): 
- Spot price is fulfilled and the instances are launched with the desired price
- Spot price can't be fulfilled: `Placed Spot instance request. Status Reason: Placed Spot instance request: sir-m6pi6f7p. Waiting for instance(s)`
- Spot price is not supported for the given instance type: `Placing Spot instance request. Status Reason: Value (t2.medium) for parameter instanceType is invalid. 't2.medium' is …
> AWS Spot price support 

- cmd/apply.go
- cmd/create.go
- cmd/root.go
create `--override` cli option for create/apply commands to
allow user to override a cluster setting.
Addresses #324
> feature allow override of cluster settings

- profiles/centosdigitalocean.go
The CentOS digital ocean cluster was failing to complete bootstrapping #393 , increasing memory on the master node to reduce memory pressure and allow the nodes to enter the ready state
> Increase DO centos master memory to 2 GB

- README.md
The README currently points to the old install guide under /docs, which has been moved/deprecated(?). I've fixed the link by pointing to the new kubicorn.io website.
> Fix installation link on README

- docs/README.md
I've updated /docs README to include how to run site. Directions are from the #366 PR
> Update /docs readme to include running site

- apis/cluster/serverpool.go
- cloud/amazon/public/resources/launchconfiguration.go
- cutil/initapi/validate.go
- cutil/initapi/validate_test.go
- test/amazon/centos_cluster_test.go
- test/amazon/ubuntu_cluster_test.go
Re issue #354 the cloud provider settings are now externalized from the API (in this case the AWS `spot price` feature) and sets the way to move forward regarding cloud specific settings. 
@kris-nova and @MyDigitalLife - from a practical experience I believe that the cloud specific settings are better placed in the `ServerPool struct` instead of `Cluster struct` as we concluded in #354 - this makes room to apply different settings per hostgroups/serverpools - going forward with the spot price example instead of adding MasterSpotPrice/NodeSpotPrice or MasterIAM/NodeIAM it's better to just have SpotPrice and IAM in the serverpool and apply to the relevant pool. For example we don't run master with spot price but node only, whereas the two groups have two different IAM roles attached.
Please …
> Externalize cloud specific settings from API 

- cutil/signals/signals.go
The (unnecessary) channel drain caused Kubicorn to hang during cluster delete - see issue #411. This is a fix for the issue.
> Bugfix - Remove not needed channel drain

- AUTHORS
- cloud/amazon/awsSdkGo/sdk.go
- cloud/amazon/awsSdkGo/sdk_test.go
- cmd/apply.go
- cmd/delete.go
- cmd/root.go
- cutil/reconciler.go
- examples/amazon/basiccluster.go
- examples/digitalocean/basiccluster.go
- examples/google/compute/basiccluster.go
- test/cluster.go
Referring to #440 
I preferred to use a different approach than setting the environment variable as proposed in the issue since the `Profile` option was already there in the Sdk.
I felt free to add a new parameter  to `cutil.GetReconciler` so that each adapter
can pass its own specific parameters needed at *runtime*.
In my opinion this is ideal since there's a whole kind of parameters that does not necessarily fits into the state, like in this case with the need to actually choose a profile from the `~/.aws/credentials` which is not related to the actual state but to the way the user want to run the whole thing at a specific moment.
Closes #440
Example:
```
kubicorn apply --aws-profile default mycluster
```
Signed-off-by: Lorenzo Fontana <lo@linux.com>
> Adding the `--aws-profile` command line option to the creational commands.

- cmd/create.go
- docs/_documentation/google-walkthrough.md
- docs/docs_old/google/walkthrough.md
Added cloud ID arg to example commands for creating a cluster with GCP as well as a suggestion on what it needs to be when the arg is unset
> Documentation around GCP and cloud ID arg

- cmd/apply.go
- cmd/create.go
- cutil/kubeadm/token.go
- cutil/namer/random.go
- cutil/parser/fileresource.go
- cutil/uuid/uuid.go
Addresses part of the #417 issue.
This PR implements `--set` logic for the `apply` command.
> cmd: implement set flag for apply

- cmd/create.go
- cutil/script/script_test.go
- examples/amazon/basiccluster.go
- examples/digitalocean/basiccluster.go
- examples/google/compute/basiccluster.go
- profiles/amazon/centos_7.go
- profiles/amazon/ubuntu_16_04.go
- profiles/azure/ubuntu.go
- profiles/digitalocean/centos_7.go
- profiles/digitalocean/ubuntu_16_04.go
- profiles/googlecompute/ubuntu_16_04.go
- state/fs/impl_test.go
- state/jsonfs/impl_test.go
- test/amazon/centos_cluster_test.go
- test/amazon/ubuntu_cluster_test.go
- test/digitalocean/centos_cluster_test.go
- test/digitalocean/ubuntu_cluster_test.go
This PR is related to #453. It was actually a straightforward renaming and moving of files. Because all the functions in the profiles exist in the `profiles` package (both before and after the refactor), there were no code changes needed as far as I could see.
I tested this by building a local binary of `kubicorn` with the new profile layout and successfully created an Ubuntu cluster on AWS.
Unfortunately I wasn't able to get `make test` running successfully (even before making any code changes) so I wasn't able to verify that the tests also didn't need any code changes, but from reading the code this seems to be okay also.
> Reorganise profiles into dirs for each provider

- cloud/google/compute/resources/instancegroup.go
- docs/_documentation/google-walkthrough.md
**Why we need this PR**
Currently, when creating an instance group/instance template on GCP, kubicorn applies the same network tags both to master and node groups, and this doesn't help if you plan to use network tags for defining firewall rules as much restrictive as possible. 
With this PR it will be possible e.g. to restrict the ingress traffic only to master nodes by defining a rule that applies only to the VMs with network tag "kubicorn-master"
**Notes for the reviewer** 
- While making the change, I restricted the existing label "http-servers" and "http-server" only to the master server group; however, I'm not sure if the "http-server" label makes sense because kubeadm init always use TLS...
- Ideally other labels could be useful, like e.g. the name of the cluster... if you are …
> Google network tags

- docs/404.html
- docs/_site/404.html
Not sure why it was needed just for 404s?
Fixes #378
> Fix 404 footer width by dropping overridden container

- cloud/amazon/public/resources/subnet.go
- profiles/amazon/centos_7.go
- profiles/amazon/ubuntu_16_04.go
The current AWS implementation is broken when it comes to correctly define subnets in the configured AZs. By default the `create` command from the model defines `Location` in the subnets definitions but in `cloud/amazon/public/resources/subnet.go:96` we are setting `Zone:  r.ClusterSubnet.Zone`. 
`r.ClusterSubnet.Zone` is not defined which causes subnets to default to a random AZ.
One would think that the quick win is to simply change the model to set the `Zone` field instead of `Location`, unfortunately this isn't working as expected due to a race condition and shared structures state in `cloud/amazon/public/resources/subnet.go`. What happens here, starting at line `:48`, is that because `r.ClusterSubnet.Identifier` is empty on cluster creation, only the `else` condition is evaluated and …
> Now AZs for both master/nodes subnets will be correctly set on cluster creation

- CONTRIBUTING.md
- apis/README.md
- bootstrap/README.md
- docs/_documentation/aws-walkthrough.md
- docs/_documentation/azure-walkthrough.md
- docs/_documentation/build.md
- docs/_documentation/google-walkthrough.md
- docs/_documentation/maintainers.md
- docs/_documentation/make.md
- docs/_documentation/readme.md
- docs/_documentation/semver.md
- test/README.md
applies to docs and all package READMEs
- Cleans up grammar and spelling errors.
- Makes 'Creating' section for aws consistent with others
- Fixes profile name errors in azure and google walthroughs
closes #473
> Clean Up Docs

- apis/cluster/instanceprofile.go
- apis/cluster/serverpool.go
- cloud/amazon/awsSdkGo/sdk.go
- cloud/amazon/public/model.go
- cloud/amazon/public/resources/instanceprofile.go
- cloud/amazon/public/resources/launchconfiguration.go
- cloud/atomic_reconciler.go
- profiles/amazon/ubuntu_16_04.go
Add InstanceProfile feature for AWS. This enables Kubernetes features like: Automatic ELB allocation, PVC handling, etc.  
This is part of #418. 
- New model element: InstanceProfile
- New resource element: InstanceProfile
- Supports Add/Delete/Update InstanceProfile
- Add InstanceProfile to LaunchConfiguration if present
- Manage InstanceProfile - Role - Policy together
- Add Cloud specific configuration to Bootstrap scripts
> Add AWS instance profile support

- docs/_documentation/aws-walkthrough.md
- docs/_documentation/minimal-aws-permissions.md
This set of actions is the minimum required for kubicorn to work on AWS,
in case users don't want to give their IAM user wide permissions.
> Document necessary IAM permissions for AWS

- bootstrap/amazon_k8s_ubuntu_16.04_node.sh
- profiles/amazon/ubuntu_16_04.go
This is related to the previous IAM support #472 PR. Contains a fix and an example of an AWS profile for Ubuntu.
> Adding IAM profile for node group and fixing kubelet service restart

- Makefile
When building kubicorn on CI systems, it's helpful for the resulting
binary to be owned by the CI user, so that it can be deleted during
clean up without permission issues. Pass in the current user/group
ID to Docker to facilitate this.
It is not passed in to the shell target, as the user is almost
guaranteed to not exist on the image, and a valid user should be present
when working in the shell.
> Pass in host user/group ID

- AUTHORS
- bootstrap/packet_k8s_ubuntu_16.04_master.sh
- bootstrap/packet_k8s_ubuntu_16.04_node.sh
The apt install order worked ok on x86, but did not on arm. This fixes the install order of `apt` packages universally.
A future PR will complete arm work (everything works except for a Calico issue).
> Fix apt order in packet bootstrap files

- cloud/amazon/public/resources/instanceprofile.go
- cloud/atomic_reconciler.go
- cutil/signals/signals.go
This PR hotfixes panics due to dereferencing nil pointer.
Currently, applying a cluster will result in panic:
```
marko@Marko:~$ kubicorn apply testcluster
2017-11-26T10:22:01+01:00 [ℹ]  Selected [fs] state store
2017-11-26T10:22:01+01:00 [ℹ]  Loaded cluster: testcluster
2017-11-26T10:22:01+01:00 [ℹ]  Init Cluster
2017-11-26T10:22:01+01:00 [ℹ]  Query existing resources
2017-11-26T10:22:04+01:00 [ℹ]  Resolving expected resources
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x20 pc=0x489222]
goroutine 1 [running]:
time.(*Timer).Stop(0x0, 0x11d8c40)
/usr/local/go/src/time/sleep.go:75 +0x22
github.com/kris-nova/kubicorn/cutil/signals.(*Handler).Reset(0xc4202eef80) …
```
> signals: fix reconciler panics

- profiles/amazon/ubuntu_16_04.go
In order for containers on nodes to use dynamic PVs, the nodes need to
have the permission to attach and detach volumes. The master has
"ec2:*", and thus doesn't need these permissions explicitly.
> Allow nodes to manage EC2 volumes

- profiles/amazon/centos_7.go
PR #507 only updated the Ubuntu profile. This updates CentOS as well.
> Allow CentOS nodes to manage EBS volumes

- .gitignore
- AUTHORS
- bootstrap/digitalocean_k8s_ubuntu_16.04_master.sh
- bootstrap/digitalocean_k8s_ubuntu_16.04_node.sh
- cutil/parser/fileresource.go
- cutil/parser/github.go
:wave:
This PR updates the the digital ocean ubuntu bootstrap scripts to install 1.9.1.
I also added some extra logging to the filesource parser, so it's more obvious what bootstrap scripts are running.
I've tested these changes locally and they work 💯.  
I was going to update other profiles, but I currently only have access to Digital Ocean instances. 
Thanks!
> Update Digital Ocean Ubuntu Profile to use k8s 1.9.1

- cmd/apply.go
- cutil/defaults/defaults.go
- cutil/kubeconfig/kubeconfig.go
Kubicorn by default appends to `~/.kube/.config` the kubeconfig file for newly created clusters.
This behaviours is more than fine when you work mainly with only one cluster, but it creates some problems when you work with many clusters at the same time (as reported in [#496](https://github.com/kris-nova/kubicorn/issues/496)).
This PR introduces a new alpha annotation at cluster level,  `cluster.alpha.kubicorn.io/kubeconfig-local-path`.
By setting this annotation in your cluster state, the kubeconfig file is saved instead in the specified path, allowing user to switch to one cluster to another e.g. by setting the `KUBENCOFIG` env var.
> new cluster annotation for kubeconfig local path

- cmd/apply.go
- cmd/create.go
- cmd/delete.go
- cmd/edit.go
- cmd/getconfig.go
- cmd/utils.go
- state/README.md
When an invalid state store is specified `kubicorn` panics [1]. Return an error instead [2].
[1] 
```
rodin:dew-drops dwat$ export KUBICORN_STATE_STORE=fake
rodin:dew-drops dwat$ /Users/dwat/workspace/go/src/github.com/kris-nova/kubicorn/kubicorn create dewAnother --profile aws
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x38 pc=0x1af5d36]
goroutine 1 [running]:
github.com/kris-nova/kubicorn/cmd.RunCreate(0x2857f20, 0x11917c0, 0xc420511ca8)
/Users/dwat/workspace/go/src/github.com/kris-nova/kubicorn/cmd/create.go:227 +0x3f6
github.com/kris-nova/kubicorn/cmd.CreateCmd.func1(0xc4202526c0, 0xc4203f4e70, 0x1, 0x3)
/Users/dwat/workspace/go/src/github.com/kris-nova/kubicorn/cmd/create.go:69 +0x72 …
```
> Return an error when an invalid state store is specified.

- apis/cluster/cluster.go
- apis/cluster/components.go
- bootstrap/digitalocean_k8s_centos_7_master.sh
- bootstrap/digitalocean_k8s_centos_7_node.sh
- bootstrap/digitalocean_k8s_ubuntu_16.04_master.sh
- bootstrap/digitalocean_k8s_ubuntu_16.04_node.sh
- bootstrap/vpn/openvpnMaster-centos.sh
- bootstrap/vpn/openvpnMaster.sh
- bootstrap/vpn/openvpnNode-centos.sh
- bootstrap/vpn/openvpnNode.sh
- cloud/digitalocean/droplet/resources/droplet.go
- cutil/defaults/defaults.go
- cutil/parser/fileresource.go
- docs/_documentation/envar.md
- profiles/digitalocean/centos_7.go
- profiles/digitalocean/ubuntu_16_04.go
This PR reworks the cluster provisioning process on DigitalOcean. This method provides a great base for further improvements, such as implementing DO CCM (#276), Dashboard or Heapster.
* [ADD] Added **Components** API structure for defining optional cluster components.
* [ADD] Added and documented the `KUBICORN_ENVIRONMENT` variable, used to instruct `kubicorn` to use local bootstrap scripts. Closes #523.
* [ADD] Create a Cloud Firewall while provisioning the CentOS clusters.
* [FIX] Wait before populating the state if `godo` returns empty string instead of an IP address.
* [FIX] Fix networking issues by adding the appropriate flag to the `kubelet` service.
* [CHANGE] Switch to WeaveNet for CNI.
* [CHANGE] VPN is disabled by default now. In order to enable it, you need to change the …
> digitalocean: rework digitalocean bootstrap scripts

- docs/_documentation/cloud-providers.md
Links into GitHub refs (for directories & code) were failing 404 due to missing some path bits.
> Fix a few documentation links to GitHub :)

- profiles/amazon/ubuntu_16_04.go
Update the AMI versions to a more recent version that mitigates the recent exploits (spectre, meltdown).
The AMI specified is in the us-west-2 region, with kernel version > 4.4.X, which contains the updates to mitigate spectre variant 1, spectre variant 2 (but requires updated firmware/microcode), and meltdown as per https://wiki.ubuntu.com/SecurityTeam/KnowledgeBase/SpectreAndMeltdown
AMI details from AWS Community AMIs: `ubuntu/images/hvm-ssd/ubuntu-xenial-16.04-amd64-server-20180126 - ami-79873901`
> Update AWS Profile's Ubuntu AMIs

- cloud/amazon/public/resources/instanceprofile.go
Since we can detect whether or not an instance profile exists via error
types, attempt to re-use an existing instance profile before returning
an error.
The name and id have to be extracted seperately since the returned
values for creating an instance profile and getting one are two
different types.
Signed-off-by: Nolan Brubaker <nolan@heptio.com>
> Use an existing instance profile if found

- cmd/apply.go
- cmd/edit.go
- cmd/explain.go
- cmd/getconfig.go
- cmd/root.go
- docs/_documentation/cloud-providers.md
- docs/_documentation/envar.md
- examples/amazon/basiccluster.go
- examples/digitalocean/basiccluster.go
- examples/google/compute/basiccluster.go
- pkg/cli/options.go
- pkg/initapi/init.go
Closes #359 
Currently, it only supports JSON format. Once we get this in I'll start working on the textual output as well.
Signed-off-by: Marko Mudrinić <mudrinic.mare@gmail.com>
> cmd: implement explain command

- AUTHORS
- pkg/kubeconfig/kubeconfig.go
When using a ssh-key with a passphrase the loop in `RetryGetConfig` always creates new agents and always add the key-file to the agent. This forces one to always enter the passphrase in every loop iteration. This PR fixes this by creating the ssh configuration once and using this configuration for the whole loop. So a passphrase must be entered only once.
> add the key to the agent only once so passphrase is only once needed

- bootstrap/google_compute_k8s_ubuntu_16.04_master.sh
- bootstrap/google_compute_k8s_ubuntu_16.04_node.sh
- cloud/google/compute/resources/instancegroup.go
- cmd/create.go
This PR fixes cluster creation and provisioning process for Google Cloud Engine.
Changelog:
```
[marko@xmudrii-1 kubicorn]$ kubectl get nodes
NAME                    STATUS    ROLES     AGE       VERSION
mycluster-master-q13f   Ready     master    2m        v1.9.2
mycluster-node-pppw     Ready     <none>    1m        v1.9.2
mycluster-node-t3bv     Ready     <none>    1m        v1.9.2
```
Sonobuoy tests: All 125 tests are passing.
> cloud,bootstrap,google: fix cluster creation and provisioning

- Dockerfile
I couldn't get the docker build to work locally because I don't have access to the kubicorn repository over SSH. Changing it to use https instead fixes this.
> Configure git to use the https protocol instead of ssh

- cmd/apply.go
- cmd/crd.go
- cmd/create.go
- cmd/delete.go
- cmd/deploycontroller.go
- cmd/edit.go
- cmd/explain.go
- cmd/getconfig.go
- cmd/list.go
- cmd/root_environment.go
- pkg/cli/options.go
without breaking pkg api contracts, allow for common flags to be pulled into function calls that add to a command those flags. Should remove a lot of duplication of code.
> [flags/cmd] place common flags into a set of functions that can be called to add them.

- pkg/cli/profiles_map.go
- profiles/digitalocean/controller_ubuntu_16_04.go
This PR adds Controller Ubuntu profile for DigitalOcean. It deploys Ubuntu 16.04 cluster in `nyc3` region contained of 1 master and 1 node.
Kubernetes version 1.9.2.
```
[xmudrii@xmudrii-1 kubicorn]$ kubectl get nodes
NAME                         STATUS    ROLES     AGE       VERSION
controller-ubuntu-master-0   Ready     master    2m        v1.9.2
controller-ubuntu-node-0     Ready     <none>    2m        v1.9.2
[xmudrii@xmudrii-1 kubicorn]$ kubectl get pods -n kubicorn
NAME                                   READY     STATUS    RESTARTS   AGE
kubicorn-controller-78f8b6bb78-zjrtw   1/1       Running   0          2m
```
> profiles,digitalocean: add controller ubuntu profile

- cloud/amazon/public/resources/instanceprofile.go
Because of this typo after an amazon cluster is updated, kubicorn is unable to delete that amazon cluster.
> Fix delete after amazon cluster update

- AUTHORS
- profiles/digitalocean/centos_7.go
- profiles/digitalocean/controller_ubuntu_16_04.go
- profiles/digitalocean/ubuntu_16_04.go
Current digitalocean based profiles don't take into account UDP internal communication when creating firewall rules. This leads to failures as nodes are not able to contact master on UDP ports (required for instance for DNS)
This Pull Request adds an UDP rule for all ports based on labels (in the same way it's already handled for TCP ports) allowing communication for UDP protocol between masters and nodes.
> Enable UDP traffic on all ports between k8s master and nodes

- cmd/apply.go
- cmd/create.go
- pkg/cli/options.go
This allows the cli flags to be repeated, such as:
-C SSH.user=somebody
-C SSH.publicKeyPath=/path/to/key.pub
Signed-off-by: Andy Goldstein <andy.goldstein@gmail.com>
> [WIP] Change Set/MasterSet/NodeSet to []string

- Makefile
This PR fixes the golint import path, which is currently causing travis builds to fail.
> Fix golint build issue (wrong import)

- .gitmodules
When executing the install command from the docs it's going to fail
because it's trying to also fetch the submodule, and it was doing that
via SSH instead of HTTPS protocol.
As a result, replace the submodule's protocol with HTTPS so that anyone
can freely issue `go get github.com/kubicorn/kubicorn` and have the binary directly compiled in their `${GOPATH}`
Resolves: #686
Related:
Signed-off-by: Daniel Andrei Minca
> fix issue with submodule protocol - cloning over SSH instead of HTTPS
